# -*- coding: utf-8 -*-
"""66-1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1r2xXSHwGhGBoQvqJDwcXXLBEe94dwQmD
"""

a=10
b=20
c=a+b
print(c)